/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courrier;

import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author user
 */
public class Acceuil extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Acceuil
     */
    Timer chrono = new Timer(15, this);
    Timer chrono1 = new Timer(35, this);
    int ax = 0;
    int bx = 0;
    int cx = 0;

    public Acceuil() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        chrono.start();
        System.out.println("Timer lancé. Ouverture Pannel1 - Lancement");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        InputLogin = new javax.swing.JTextField();
        InputPass = new javax.swing.JPasswordField();
        ButtAnnuler = new javax.swing.JButton();
        ButtConnecter = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(439, 300));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(439, 300));
        jPanel1.setLayout(null);
        jPanel1.setVisible(false);

        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(430, 0, 10, 300);

        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 1, 10, 300);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 140, 40, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lock.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 190, 24, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_coud_1-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 20, 251, 101);

        InputLogin.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        InputLogin.setForeground(new java.awt.Color(153, 153, 153));
        InputLogin.setText("Nom d'utilisateur");
        InputLogin.setToolTipText("");
        InputLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputLoginFocusLost(evt);
            }
        });
        InputLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputLoginActionPerformed(evt);
            }
        });
        jPanel1.add(InputLogin);
        InputLogin.setBounds(130, 140, 210, 38);

        InputPass.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        InputPass.setForeground(new java.awt.Color(153, 153, 153));
        InputPass.setText("000000000000000");
        InputPass.setMaximumSize(new java.awt.Dimension(12, 28));
        InputPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputPassFocusLost(evt);
            }
        });
        InputPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPassActionPerformed(evt);
            }
        });
        jPanel1.add(InputPass);
        InputPass.setBounds(130, 190, 210, 40);

        ButtAnnuler.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ButtAnnuler.setText("Annuler");
        ButtAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtAnnulerActionPerformed(evt);
            }
        });
        jPanel1.add(ButtAnnuler);
        ButtAnnuler.setBounds(250, 240, 90, 37);

        ButtConnecter.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ButtConnecter.setText("Se Connecter");
        ButtConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtConnecterActionPerformed(evt);
            }
        });
        jPanel1.add(ButtConnecter);
        ButtConnecter.setBounds(130, 240, 122, 37);

        setLocationRelativeTo(null);
        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fond1.png"))); // NOI18N
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 10, 1190, 280);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 440, 300);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        setLocationRelativeTo(null);
        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1440f9ca0119484d9a81d8b0981c59c6.gif"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 10, 280, 250);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPassActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_InputPassActionPerformed

    private void ButtAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtAnnulerActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtAnnulerActionPerformed

    private void ButtConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtConnecterActionPerformed
        if (InputLogin.getText().equals("MSGB") && InputPass.getText().equals("123456")) {

            Principal Pr = new Principal();

            chrono1.stop();
            System.out.println("Identification réussie. Ouverture Pannel1 - Principal().Menu");
            Pr.setVisible(true);
            setVisible(false);
            chrono1.stop();
        } else {
            JOptionPane.showMessageDialog(null, "Le Nom d'utilisateur ou le Mot de passe est incorrect, veuillez réessayer !!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtConnecterActionPerformed

    private void InputLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputLoginActionPerformed

    private void InputLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputLoginFocusGained
        if ("Nom d'utilisateur".equals(InputLogin.getText())) {
            InputLogin.setText("");
            InputLogin.setForeground(new java.awt.Color(0, 0, 0));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_InputLoginFocusGained

    private void InputLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputLoginFocusLost
        if ("".equals(InputLogin.getText())) {
            InputLogin.setText("Nom d'utilisateur");
            InputLogin.setForeground(new java.awt.Color(153, 153, 153));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_InputLoginFocusLost

    private void InputPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputPassFocusGained
        if ("000000000000000".equals(InputPass.getText())) {
            InputPass.setText("");
            InputPass.setForeground(new java.awt.Color(0, 0, 0));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPassFocusGained

    private void InputPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputPassFocusLost
        if ("".equals(InputPass.getText())) {
            InputPass.setText("000000000000000");
            InputPass.setForeground(new java.awt.Color(153, 153, 153));
        }
// TODO add your handling code here:
    }//GEN-LAST:event_InputPassFocusLost

    public void mouvement() {
        if (bx != 350) {
            bx = bx + 1;
            jLabel4.setBounds(10 - bx, 10, 790, 280);

            //System.out.println("Gauche " + bx);
        } else {
            cx = cx + 1;
            jLabel4.setBounds(10 - bx + cx, 10, 790, 280);

            //System.out.println("Droite " +cx);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceuil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtAnnuler;
    private javax.swing.JButton ButtConnecter;
    private javax.swing.JTextField InputLogin;
    private javax.swing.JPasswordField InputPass;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (ax != 100) {
            ax = ax + 1;

        } else if (ax == 99) {
            System.out.println("Timer arrété. Ouverture Pannel1 - Connection");
        } else {

            jPanel1.setVisible(true);
            jPanel2.setVisible(false);
            chrono.stop();
            chrono1.start();
            mouvement();
            if (cx == 350) {
                bx = 0;
                cx = 0;
                mouvement();

            }

        }
    }
}
